export class GradeNotFound extends Error {}
export class GradeConflict extends Error {}
export class InvalidJudgments extends Error {}
export class GradeIncomplete extends Error {}
export class InvalidGradingConfiguration extends Error {}
export class GradingRecordsExist extends Error {}
export class InvalidMark extends Error {}
export class MarkNotFound extends Error {}
export class MarkConflict extends Error {}
export class MarkIncomplete extends Error {}
