export class ClassAlreadyConfigured extends Error {}
export class ClassNotConfigured extends Error {}
export class SeatAlreadyActive extends Error {}
export class SeatAlreadyExists extends Error {}
export class SeatNotActive extends Error {}
export class SeatNotDropped extends Error {}
export class SeatNotFound extends Error {}
export class SeatNotPending extends Error {}
export class SectionNotFound extends Error {}
